/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jetbrains_numkt_Interpreter */

#ifndef _Included_org_jetbrains_numkt_Interpreter
#define _Included_org_jetbrains_numkt_Interpreter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jetbrains_numkt_Interpreter
 * Method:    initializePython
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_numkt_Interpreter_initializePython
    (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_jetbrains_numkt_Interpreter
 * Method:    callFunc_00024kotlin_numpy
 * Signature: ([Ljava/lang/String;[Ljava/lang/Object;Ljava/util/Map;)Lorg/jetbrains/numkt/core/KtNDArray;
 */
JNIEXPORT jobject JNICALL
Java_org_jetbrains_numkt_Interpreter_callFunc_00024kotlin_1numpy___3Ljava_lang_String_2_3Ljava_lang_Object_2Ljava_util_Map_2
    (JNIEnv *, jobject, jobjectArray, jobjectArray, jobject);

/*
 * Class:     org_jetbrains_numkt_Interpreter
 * Method:    callFunc_00024kotlin_numpy
 * Signature: ([Ljava/lang/String;[Ljava/lang/Object;Ljava/util/Map;Ljava/lang/Class;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL
Java_org_jetbrains_numkt_Interpreter_callFunc_00024kotlin_1numpy___3Ljava_lang_String_2_3Ljava_lang_Object_2Ljava_util_Map_2Ljava_lang_Class_2
    (JNIEnv *, jobject, jobjectArray, jobjectArray, jobject, jclass);

/*
 * Class:     org_jetbrains_numkt_Interpreter
 * Method:    getField_00024kotlin_numpy
 * Signature: (Ljava/lang/String;JLjava/lang/Class;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_jetbrains_numkt_Interpreter_getField_00024kotlin_1numpy
    (JNIEnv *, jobject, jstring, jlong, jclass);

/*
 * Class:     org_jetbrains_numkt_Interpreter
 * Method:    getValue_00024kotlin_numpy
 * Signature: (J[J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_jetbrains_numkt_Interpreter_getValue_00024kotlin_1numpy__J_3J
    (JNIEnv *, jobject, jlong, jlongArray);

/*
 * Class:     org_jetbrains_numkt_Interpreter
 * Method:    getValue_00024kotlin_numpy
 * Signature: (J[Lorg/jetbrains/numkt/core/Slice;)Lorg/jetbrains/numkt/core/KtNDArray;
 */
JNIEXPORT jobject JNICALL
Java_org_jetbrains_numkt_Interpreter_getValue_00024kotlin_1numpy__J_3Lorg_jetbrains_numkt_core_Slice_2
    (JNIEnv *, jobject, jlong, jobjectArray);

/*
 * Class:     org_jetbrains_numkt_Interpreter
 * Method:    setValue_00024kotlin_numpy
 * Signature: (J[JLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_numkt_Interpreter_setValue_00024kotlin_1numpy__J_3JLjava_lang_Object_2
    (JNIEnv *, jobject, jlong, jlongArray, jobject);

/*
 * Class:     org_jetbrains_numkt_Interpreter
 * Method:    setValue_00024kotlin_numpy
 * Signature: (J[Lorg/jetbrains/numkt/core/Slice;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL
Java_org_jetbrains_numkt_Interpreter_setValue_00024kotlin_1numpy__J_3Lorg_jetbrains_numkt_core_Slice_2Ljava_lang_Object_2
    (JNIEnv *, jobject, jlong, jobjectArray, jobject);

/*
 * Class:     org_jetbrains_numkt_Interpreter
 * Method:    freeArray_00024kotlin_numpy
 * Signature: (JLjava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_numkt_Interpreter_freeArray_00024kotlin_1numpy
    (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_jetbrains_numkt_Interpreter
 * Method:    closePython
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_numkt_Interpreter_closePython
    (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
