/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jetbrains_numkt_core_KtNDIter */

#ifndef _KTNDITER_H_
#define _KTNDITER_H_
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jetbrains_numkt_core_KtNDIter
 * Method:    iterNew
 * Signature: (Lorg/jetbrains/numkt/core/KtNDArray;[Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_jetbrains_numkt_core_KtNDIter_iterNew
    (JNIEnv *, jobject, jobject, jobjectArray, jstring);

/*
 * Class:     org_jetbrains_numkt_core_KtNDIter
 * Method:    indexGet
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_numkt_core_KtNDIter_indexGet
    (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jetbrains_numkt_core_KtNDIter
 * Method:    indexSet
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_numkt_core_KtNDIter_indexSet
    (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_jetbrains_numkt_core_KtNDIter
 * Method:    iterIndexGet
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_numkt_core_KtNDIter_iterIndexGet
    (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jetbrains_numkt_core_KtNDIter
 * Method:    iterIndexSet
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_numkt_core_KtNDIter_iterIndexSet
    (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_jetbrains_numkt_core_KtNDIter
 * Method:    iterSizeGet
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_numkt_core_KtNDIter_iterSizeGet
    (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jetbrains_numkt_core_KtNDIter
 * Method:    multiIndexGet
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_org_jetbrains_numkt_core_KtNDIter_multiIndexGet
    (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jetbrains_numkt_core_KtNDIter
 * Method:    multiIndexSet
 * Signature: (J[I)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_numkt_core_KtNDIter_multiIndexSet
    (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     org_jetbrains_numkt_core_KtNDIter
 * Method:    iterRangeGet
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_jetbrains_numkt_core_KtNDIter_iterRangeGet
    (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jetbrains_numkt_core_KtNDIter
 * Method:    iterRangeSet
 * Signature: (JLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_numkt_core_KtNDIter_iterRangeSet
    (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_jetbrains_numkt_core_KtNDIter
 * Method:    ndimGet
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jetbrains_numkt_core_KtNDIter_ndimGet
    (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jetbrains_numkt_core_KtNDIter
 * Method:    shapeGet
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_org_jetbrains_numkt_core_KtNDIter_shapeGet
    (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jetbrains_numkt_core_KtNDIter
 * Method:    valueGet
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_jetbrains_numkt_core_KtNDIter_valueGet
    (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jetbrains_numkt_core_KtNDIter
 * Method:    dealloc
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_numkt_core_KtNDIter_dealloc
    (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jetbrains_numkt_core_KtNDIter
 * Method:    nextC
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_jetbrains_numkt_core_KtNDIter_nextC
    (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jetbrains_numkt_core_KtNDIter
 * Method:    iterClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_numkt_core_KtNDIter_iterClose
    (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jetbrains_numkt_core_KtNDIter
 * Method:    iterDebugPrintCritical
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jetbrains_numkt_core_KtNDIter_iterDebugPrintCritical
    (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jetbrains_numkt_core_KtNDIter
 * Method:    iterDebugPrintCritical
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL JavaCritical_org_jetbrains_numkt_core_KtNDIter_iterDebugPrintCritical
    (jlong);

/*
 * Class:     org_jetbrains_numkt_core_KtNDIter
 * Method:    iterNextC
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jetbrains_numkt_core_KtNDIter_iterNextC
    (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jetbrains_numkt_core_KtNDIter
 * Method:    iterRemoveAxis
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jetbrains_numkt_core_KtNDIter_iterRemoveAxis
    (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_jetbrains_numkt_core_KtNDIter
 * Method:    iterRemoveMultiIndex
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jetbrains_numkt_core_KtNDIter_iterRemoveMultiIndex
    (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jetbrains_numkt_core_KtNDIter
 * Method:    iterReset
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jetbrains_numkt_core_KtNDIter_iterReset
    (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jetbrains_numkt_core_KtNDIter
 * Method:    finishedGetCritical
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jetbrains_numkt_core_KtNDIter_finishedGetCritical
    (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jetbrains_numkt_core_KtNDIter
 * Method:    finishedGetCritical
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL JavaCritical_org_jetbrains_numkt_core_KtNDIter_finishedGetCritical
    (jlong);

#ifdef __cplusplus
}
#endif
#endif // _KTNDITER_H_
